services:
  backend:
    build: 
      context: ./tramite-app/backend
      dockerfile: Dockerfile
    container_name: tramite-backend
    volumes:
      - ./tramite-app/backend:/app
      - ./tramite-app/backend/uploads:/app/uploads
    ports:
      - "5075:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: always
    command: sh -c "mkdir -p /app/uploads && flask run --host=0.0.0.0"

  frontend:
    build:
      context: ./tramite-app/frontend
      dockerfile: Dockerfile
    container_name: tramite-frontend
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:alpine
    container_name: tramite-nginx
    ports:
      - "80:80"   # Puerto estándar HTTP, sin SSL
    volumes:
      - ./tramite-app/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./tramite-app/frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: always 